language: python

sudo: required

# safelist
branches:
  only:
  - master

services:
      - docker

install:
      - docker build -t neurodata/ndreg .
      - docker run -d -p 8888:8888 --name ndreg-vik neurodata/ndreg

script:
      - docker ps | grep -q ndreg-vik
    
after_success:
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker push neurodata/ndreg
