language: python

sudo: required

services:
      - docker

install:
    - docker build -t neurodata/ndreg .
    - docker run -p 8888:8888 --name ndreg-vik neurodata/ndreg

script:
    -  docker ps | grep -q ndreg-vik
